# ah
name: Quark

# basic
verbose: true
silent: false

# input
data: ['items.csv']

# output
stub: items
overwrite: false
backup: true

# sql
hostname: 127.0.0.1
database: clayxidb
username: clayxi
password: blaze
fail: true

# broker
restock: 3600
tick: 30

# scrub
server: asura
threads: 8
itemids: []
stock01: 5
stock12: 5
urls: []
